import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gundi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Gundi
        </h1>

        <p className={styles.description}>
          Get started by creating an account.
        </p>
        <form action="/send-data-here" method="post">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" />
          <label for="password">password</label>
          <input type="text" id="password" name="password" />
          <button type="submit">Login</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <p>Created by Zanyar Rashid</p>
      </footer>
    </div>
  )
}
