import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';
import Paragraph from "../components/elements/paragraph";
import LoginBtn from '../components/elements/login-btn';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gundi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> 
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='main-body homepage'>
      <Header />
        <div className='section'>
          <div className='row'>
            <Paragraph paragraph="Get started by creating an account."/>
            <form className='form' action="/api/auth/[..nextauth].js" method="post">
              <label for="name">Name</label>
              <input type="text" id="name" name="name" />
              <label for="password">password</label>
              <input type="text" id="password" name="password" />
              <LoginBtn />
            </form>
          </div>
        </div>
        <Footer copyright="ⓒ Goherzi Digital Media" author="Zanyar Rashid"/>
      </main>
    </div>
  )
}
